globaldothealth/isaric

.gitignore
isaric/parser.py
isaric/parsers/isaric-ccpuk.json
isaric/schemas.py
poetry.lock
pyproject.toml

- Add tqdm dependency
- isaric: add parser for subject table
- parsers(isaric-ccpuk): move primaryKey, use booleans and nulls
- schemas: rename ReferenceDateType -> ReferenceDate
- gitignore: ignore CSV, XLSX files

add subject parser

---

isaric/parser.py
isaric/parsers/isaric-ccpuk.json
isaric/schemas.py
isaric/taxonomy/v1.json
poetry.lock
pyproject.toml

Add support for parsing visits

Parse visits

---

docs/spec-format.md
isaric/parser.py
tests/test_parser.py

docs: visits are supported now, merge with subject
Fixes: #18

parser: add support for combinedType=list

---

isaric/parser.py
tests/test_parser.py

Add conditional support to transformation specification

---

docs/spec-format.md
isaric/parser.py
requirements.txt
tests/test_parser.py

I think this should be sufficient for transforming the ethnicity field @ekamau? Let me know if there's anything else I can add to this feature.

Add exclude functionality to list, fixes #31

---

isaric/parser.py
isaric/parsers/isaric-ccpuk.json

- wip
- Make parser code generic
- parsers(ccpuk): support the generic parser

generic parser

---

.vscode/settings.json
isaric/parsers/isaric-ccpuk.toml

The black formatter is stopping indentation in the toml files at the moment, might want to consider a different formatter to use with toml files going forward.

Added treatment_neuraminidase to ccpuk parser (TOML style)

---

isaric/parsers/isaric-ccpuk.toml
isaric/schemas.py

Removed the treatment_oxygen_interface and treatment_oxygen_ mechanical_support attributes as duplicates of treatment_oxygen_therapy.
Addressing #61

Parsers(ccpuk): remove oxygen_therapy duplicates

---

.gitignore
isaric/parsers/isaric-rapid.toml

Most of these I'm happy with, the only question is the ordering of ccm_a_* vs ccm_b_*

Re-ordered priority of mappings for rapid visits

---

isaric/parsers/isaric-ccpuk.toml
schemas/dev/parser.schema.json
schemas/dev/subject.schema.json

Add parser validation to schema.
parser.schema.json is a JSON schema for the adtl parser files in TOML
format.  This adds autocompletion and validation with the EvenBetterTOML
extension for VS Code, with the schema comment at the top of parser
files:
```
#:schema ../../schemas/dev/parser.schema.json
```

validate parser

---

isaric/parsers/isaric-ccpuk.toml
isaric/parsers/isaric-rapid.toml
schemas/dev/parser.schema.json
schemas/dev/visit.schema.json

Addresses #86 
Couple of questions to address particularly in the rapid parser, where there is a 'list' combinedType to get the values but more than one set of fields for each which will require a 'firstNonNull' option as well.

Track drug types

---

autoparser/a.md
autoparser/isaric-bak.toml
autoparser/isaric.toml
isaric/parsers/datcov-southafrica.toml
isaric/parsers/ecmo_subject.toml
output/ISARIC CCPUK/adtl-output.txt
schemas/dev/create_parser_schema.py
schemas/dev/observation.schema.json
schemas/dev/subject.schema.json
schemas/dev/visit.schema.json

- schemas(subject): remove enum for ethnicity
- schemas: use uniqueItems for all arrays
- schemas(subject): allow age to be zero

schema fixes

---

autoparser/README.md
autoparser/autoparser/__main__.py
autoparser/autoparser/csv_mapping.py
autoparser/autoparser/make_toml.py
autoparser/autoparser/util.py
autoparser/pyproject.toml

This PR adds a `-k`, `--check` flag to estimate the accuracy of autoparser predictions against a parser. Also added lemmatization to improve matches

Estimate and improve accuracy in autoparser

---

isaric/parsers/ccp-guinea.toml
output/CCP GUINEA/adtl-output.md

*Notes*: Source file has encoding iso-8859-1, run with adtl option `--encoding`
*Questions*:
*Validation*:
|table       	|valid	|total	|percentage_valid|
|---------------|-------|-------|----------------|
|subject       	|2720	|2741	|99.233856% |
|visit         	|2665	|2741	|97.227289% |
|observation   	|203231	|219401	|92.629933% |
* 19: data must contain ['admission_date', 'age', 'country_iso3', 'pathogen', 'sex_at_birth', 'subject_id'] 
properties
* 2: data.pregnancy_gestational_assessment_weeks must be number
* 76: data must contain ['visit_id', 'subject_id', 'country_iso3', 'start_date', 'outcome', 'date_outcome'] 
properties
* 16170: data must contain ['phase', 'date', 'name'] properties

parsers: add ccp-guinea

---

schemas/dev/parser.schema.json
schemas/dev/visit.schema.json
templates/template_parser.toml

Already captured in other oxygen therapy fields

schemas: remove treatment_oxygen_interface (bool)

---

autoparser/README.md
autoparser/autoparser/csv_mapping.py
autoparser/autoparser/make_toml.py
autoparser/pyproject.toml

- autoparser: handle missing category
- autoparser: allow XLSX format data dictionary
- autoparser(docs): add intermediate schema

autoparser misc fixes

---

ci/validate_parser.py
docs/guide.rst
isaric/parsers/ccp-guinea.toml
isaric/parsers/ccp-senegal.toml
isaric/parsers/western-australia.toml
schemas/dev/parser.schema.json
schemas/dev/subject.schema.json

Creates a 'sex' option to use where sex *at birth* has not been specified.

Option for distinguishing sex and sex_at_birth

---

docs/guide.rst
isaric/parsers/ccp-drc.toml
isaric/parsers/cocoa_pediatrics.toml
isaric/parsers/ncov-malaysia.toml
schemas/dev/observation.schema.json
schemas/dev/parser.schema.json
schemas/dev/subject.schema.json
schemas/dev/visit.schema.json

* Started using oxygen_o2hb for haemoglobin count
* Introduced the treatment_oxygen_mask_prongs field as noted in the guide
* Increased the max respiratory rate from 50 to 90 to reflect higher rates for infants
* Allow birthweight to be a string with pattern matching for a range of values

COCOA paediatrics parser

---

isaric/parsers/ncov-phosp.toml

First draft of the ncov phosp parser

ncov PHOSP parser

---

autoparser/autoparser/csv_mapping.py
autoparser/tests/__snapshots__/test_make_toml.ambr
autoparser/tests/isaric-subject.csv
autoparser/tests/test_make_toml.py
docs/guide.rst
isaric/parsers/cocoa_pediatrics.toml
isaric/parsers/lmic.toml
schemas/dev/observation.schema.json
schemas/dev/parser.schema.json
schemas/dev/visit.schema.json
templates/template_parser.toml

|table          |valid  |total  |percentage_valid|
|---------------|-------|-------|----------------|
|subject        |432    |434    |99.539171% |
|visit          |434    |434    |100.000000% |
|observation    |16925  |16926  |99.994092% |
* 2: data.age must be bigger than or equal to 0
* 1: data must be valid exactly by one definition (0 matches found)

LMIC parser

---

isaric/parsers/ccp-cameroon.toml

initial draft of CCP Cameroon study

first draft parser CCP cameroon

---

isaric/parsers/stopcovid-russia.toml
isaric/parsers/stopcovid-russia/merge_acute_followup_data.py
output/stopcovid-russia/adtl-output.md

- parsers: add stopcovid-russia
- update
- update

stopcovid russia

---

isaric/parsers/ccp-ghana.toml
isaric/parsers/ccp-guinea.toml
isaric/parsers/ccp-spain.toml
isaric/parsers/ccp-uganda-v2.toml
isaric/parsers/datcov-southafrica.toml
isaric/parsers/isaric-ccpuk.toml
isaric/parsers/isaric-ecmo.toml
isaric/parsers/isaric-rapid.toml
isaric/parsers/ncov-france.toml
isaric/parsers/sprintsari-australia.toml
isaric/parsers/western-australia.toml

plus made attribute super-type where necessary
Added mask_prongs attribute to relevant parsers
This only covers parsers that are currently in main, not those still at the pull request stage.

Added ecmo to oxygen_therapy attribute

---

isaric/parsers/isaric-ecmo.toml
output/ISARIC ECMO/adtl-output.md

Plus small fixes to observation table to bump up pass rate.
@sadiekelly I'm tagging this as 'needs review' as a reminder that I don't think the observation table was ever checked - but it can go on the bottom of the to-do list!

Add RELSUB to ECMO parser, Observation table review

---

isaric/parsers/ccp-cameroon.toml
isaric/parsers/ccp-drc.toml
isaric/parsers/ccp-ghana.toml
isaric/parsers/ccp-guinea.toml
isaric/parsers/ccp-netherlands.toml
isaric/parsers/ccp-senegal.toml
isaric/parsers/ccp-spain.toml
isaric/parsers/ccp-uganda-v2.toml
isaric/parsers/cocoa_pediatrics.toml
isaric/parsers/datcov-southafrica.toml
isaric/parsers/idor-brazil.toml
isaric/parsers/isaric-ccpuk.toml
isaric/parsers/isaric-ecmo.toml
isaric/parsers/isaric-followup-fr.toml
isaric/parsers/isaric-rapid.toml
isaric/parsers/isaric-tier1.toml
isaric/parsers/isaric_washington.toml
isaric/parsers/lmic.toml
isaric/parsers/ncov-france.toml
isaric/parsers/ncov-gambia.toml
isaric/parsers/ncov-malaysia.toml
isaric/parsers/ncov-phosp.toml
isaric/parsers/predicovid.toml
isaric/parsers/recover-eu.toml
isaric/parsers/sprintsari-australia.toml
isaric/parsers/stopcovid-russia.toml
isaric/parsers/uganda-vri-v1.toml
isaric/parsers/western-australia.toml
templates/template_parser.toml

Added musculoskeletal pain to observation table

adding musculoskeletal_pain to parsers

---

isaric/parsers/ccp-cameroon.toml
isaric/parsers/ccp-drc.toml
isaric/parsers/ccp-ghana.toml
isaric/parsers/ccp-guinea.toml
isaric/parsers/ccp-netherlands.toml
isaric/parsers/ccp-senegal.toml
isaric/parsers/ccp-spain.toml
isaric/parsers/ccp-uganda-v2.toml
isaric/parsers/datcov-southafrica.toml
isaric/parsers/idor-brazil.toml
isaric/parsers/isaric-ccpuk.toml
isaric/parsers/isaric-rapid.toml
isaric/parsers/lmic.toml
isaric/parsers/ncov-malaysia.toml
isaric/parsers/sprintsari-australia.toml
isaric/parsers/uganda-vri-v1.toml
isaric/parsers/western-australia.toml

Splits works_lab additions out from #188 to close #187

Add works_lab
